SELECT * FROM PROFESSOR;
-- BONUS 를 받는 교수들만 출력
-- 급여가 300~400 사이인 교수들 출력.
SELECT *
FROM PROFESSOR
WHERE PAY BETWEEN 300 AND 400;
-- 아이디에 'a'가 들어가는 교수 출력
SELECT *
FROM PROFESSOR
WHERE ID LIKE('%a%');
-- PROFNO, NAME, ID를 임의로 넣어서 교수 레코드 INSERT
INSERT INTO PROFESSOR(PROFNO, NAME, ID, POSITION,PAY,HIREDATE)
VALUES(5005, '김민호', 'kimtiger', '조교수', 250,'25/02/26');
COMMIT;
-- 4번에서 만든 데이터 DELETE
DELETE FROM PROFESSOR WHERE PROFNO = '5005';
COMMIT;
-- 급여가 300 이하인 교수들의 급여를 +10 UPDATE
UPDATE PROFESSOR SET
PAY = PAY + 10
WHERE PAY <= 300;
COMMIT;