
CREATE OR REPLACE TRIGGER EMP_TRIGGER
    BEFORE
    INSERT OR UPDATE OR DELETE ON EMP
    FOR EACH ROW
BEGIN
-- SYS_CONTEXT('USERENV', 'SESSION_USER') 
--현재 아이디를 가져오는 문법

    IF :NEW.COMM IS NULL OR :NEW.COMM < 0 THEN
        :NEW.COMM := 0;
    END IF;
    
    IF INSERTING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :NEW.MGR, :OLD.SAL, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U', SYSDATE);
    ELSIF DELETING THEN
        -- INSERT INTO EMP_LOG
        --VALUES(:OLD.EMPNO, :OLD.MGR, :OLD.SAL, :OLD.SAL, :OLD.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'D', SYSDATE);
        RAISE_APPLICATION_ERROR(-20003, '사원의 데이터는 삭제할 수 없습니다.');
    
    END IF;
END;
/
    SELECT * FROM
    EMP_LOG;
    
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
    FROM DUAL;
    SELECT *FROM EMP;
UPDATE EMP
SET SAL = 2050
    WHERE EMPNO = 7521;
    COMMIT;
    
    
INSERT INTO EMP(EMPNO, ENAME,SAL)
VALUES('9876','PARK',2500);

INSERT INTO EMP(EMPNO, ENAME, SAL, COMM)
VALUES('1122', 'ABCD', 9999, -300);