-- STUDENT, ENROL, SUBJECT 
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
-- 1. 성이 '김'씨인 학생들의 학번, 이름, 학과를 출력하시오.
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_NAME LIKE '%김%';
-- 2. 15학번 학생들의 학번, 이름, 학과를 출력하시오.
SELECT  
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NO, 3,2) = 15
;
-- 3. 컴퓨터정보 학과 학생들의 시험 평균 점수를 구하시오.
SELECT STU_NAME,STU_DEPT 학과 ,AVG(ENR_GRADE) 평균점수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE STU_DEPT = '컴퓨터정보'
GROUP BY S.STU_NO, STU_NAME,STU_DEPT;
--HAVING STU_DEPT = '컴퓨터정보';

-- 4. 컴퓨터개론 수업을 듣는 학생의 학번, 이름, 학과, 시험점수를 구하시오.
SELECT S.STU_NO, STU_NAME, S.STU_DEPT, ENR_GRADE
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB.SUB_NAME = '컴퓨터개론'
;

-- 5. 학생들의 전체 평균 키보다 큰 키를 가진 학생들의 학번, 이름, 키를 출력하시오.
SELECT AVG(STU_HEIGHT)
FROM STUDENT;

SELECT STU_NO, STU_NAME, STU_HEIGHT
FROM STUDENT
WHERE STU_HEIGHT >
    (
    SELECT AVG(STU_HEIGHT)
    FROM STUDENT
    )
    ORDER BY STU_HEIGHT DESC
;
-- 6. 본인 학과의 평균 키보다 큰 학생들의 이름, 학과, 키, 학과 평균키 값 출력
SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT S.STU_NAME, S.STU_DEPT,S.STU_HEIGHT,AVG_HEIGHT
FROM STUDENT S
INNER JOIN
    (
    SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1) AS AVG_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
    )
T ON S.STU_DEPT = T.STU_DEPT
WHERE STU_HEIGHT >AVG_HEIGHT
;
-- EMP, SALGRADE, DEPT
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;  
-- 1. 급여 등급이 3이상인 사원의 사번, 이름, 급여등급을 출력하시오.

-- 2. 사번, 이름, 팀장(MGR)의 이름을 출력하시오.
SELECT E1.EMPNO, E1.ENAME, E2.ENAME
FROM EMP E1 
LEFT JOIN EMP E2 ON E1.MGR = E2.EMPNO
;
-- 3. 부서별 가장 높은 급여를 받는 사원의 사번, 이름, 급여, 부서명을 출력하시오.
SELECT MAX(SAL)
FROM EMP E
WHERE DEPTNO = E.DEPTNO
;

SELECT EMPNO, ENAME, SAL, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP 
    WHERE DEPTNO = E.DEPTNO
)
;

-- 4. 입사년도가 1981년도인 사원들의 급여 총합을 구하시오.
SELECT SUM(SAL)
FROM EMP
WHERE SUBSTR(HIREDATE, 1,2) = 81;


-- STU, PROFESSOR, DEPARTMENT
SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

-- 1. 남자이면서(주민번호 7번째자리 1) 공과대학에 속한 학생의 수를 구하시오.
SELECT COUNT(*) AS 학생수
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
WHERE SUBSTR(JUMIN,7,1) = '1' AND D2.DNAME = '공과대학';

-- 2. 학생들의 아이디의 마지막 세글자를 '*' 로 채우시오
SELECT
    RPAD(SUBSTR(ID, 1, LENGTH(ID)-3), LENGTH(ID), '*') ID,
    SUBSTR(ID, 1, LENGTH(ID)-3) || '***'
FROM STU;

-- 3. 보너스+급여가 400 이하인 교수들의 이름, 아이디, 학과명을 출력하시오.

SELECT NAME, ID, D.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
WHERE PAY+NVL(BONUS,0) <= 400
GROUP BY PROFNO,NAME,ID,D.DNAME;

-- 4. 담당 학생이 2명이상인 교수의 이름, 아이디, 담당학생 수를 출력하시오.

SELECT P.NAME,
       P.ID,
       COUNT(S.STUNO) AS 담당학생수
FROM PROFESSOR P
LEFT JOIN STU S ON P.PROFNO = S.PROFNO
GROUP BY P.PROFNO, P.NAME, P.ID
HAVING COUNT(S.STUNO) >= 2;