-- 학번, 이름, 학과, 시험 평균 점수를 출력하는 STUDENT_VIEW를 만드시오
CREATE OR REPLACE VIEW STUDENT_VIEW AS 
SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE) AS AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT
WITH READ ONLY;

SELECT *
FROM STUDENT_VIEW;

