-- PL/SQL
-- 사용자 정의 함수, 프로시저, 트리거

-- PL/SQL
-- 선언부(선택), 실행부, 예외처리(선택)
-- 마지막을 '/'로 마무리

-- 숫자를 2배로 돌려주는 함수 생성
CREATE OR REPLACE FUNCTION MULTI(I_VALUE IN NUMBER)
RETURN NUMBER
IS
-- 변수 선언 (생략 가능)
BEGIN
-- 실행부
    RETURN I_VALUE * 2;
END;
/


SELECT ENR_GRADE,MULTI(ENR_GRADE)
FROM ENROL;


-- DATE_FUNC 이름의 함수를 생성
--
CREATE OR REPLACE FUNCTION DATE_FUNC(I_DATE IN DATE)
RETURN VARCHAR2
IS

BEGIN
    RETURN TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
END;
/


SELECT * 
FROM TBL_BOARD;

SELECT 
    B.*,
    DATE_FUNC(CDATETIME)
FROM TBL_BOARD B;

-- DATE_FUNC2(CDATETIME, 'DATETIME') -> 'YYYY-MM-DD HH24:MI:SS'
-- DATE_FUNC2(CDATETIME, 'DATE') -> 'YYYY-MM-DD'
-- DATE_FUNC2(CDATETIME, 'TIME') -> 'HH24:MI:SS'

CREATE OR REPLACE FUNCTION DATE_FUNC2(I_DATE IN DATE, I_KEY IN VARCHAR2)
RETURN VARCHAR2
IS
    O_DATE VARCHAR2(100);
BEGIN
    IF I_KEY = 'DATETIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
    ELSIF I_KEY = 'DATE' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD');
    ELSIF I_KEY = 'TIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'HH24:MI:SS');
    ELSE
        O_DATE := '값 잘못 입력했음ㅋ';
    END IF;
    
    RETURN O_DATE;
END;
/

SELECT 
    DATE_FUNC2(CDATETIME,'DATETIME') || '  ',
    DATE_FUNC2(CDATETIME,'DATE') || '  ',
    DATE_FUNC2(CDATETIME,'TIME') 
FROM TBL_BOARD;

ROLLBACK;

-- GRADE_FUNC
-- GRADE_FUNC(ENR_GRADE)
-- ENR_GRADE 값이 90 이상이면 'A' 리턴
-- ENR_GRADE 값이 80 이상이면 'B' 리턴
-- ENR_GRADE 값이 70 이상이면 'C' 리턴
-- ENR_GRADE 값이 60 이상이면 'D' 리턴
-- 그외에는 'F'리턴

CREATE OR REPLACE FUNCTION GRADE_FUNC (I_GRADE IN NUMBER)
RETURN VARCHAR2 
IS
BEGIN
    IF I_GRADE > 100 OR I_GRADE < 0 THEN
    RETURN '잘못된 숫자 입력';
    ELSIF I_GRADE >= 90 THEN
        RETURN 'A';
    ELSIF I_GRADE >= 80 THEN
        RETURN 'B';
     ELSIF I_GRADE >= 70 THEN
        RETURN 'C';
    ELSIF I_GRADE >= 60 THEN
        RETURN 'D';
    ELSE 
        RETURN 'F';
     END IF;
END;
/

SELECT ENR_GRADE,GRADE_FUNC(ENR_GRADE) 
FROM 
ENROL;

SELECT *
FROM STU;

-- GENDER_FUNC(JUMIN)
-- 7번째 숫자가 1이랑 3이면 남자 리턴
-- 2,4 면 여자 리턴
-- 인자값이 13자리가 아니면 '제대로 값 입력하셈' 리턴
CREATE OR REPLACE FUNCTION GENDER_FUNC(I_JUMIN IN VARCHAR2)
RETURN VARCHAR2 
IS
    O_GENDER CHAR(1);
BEGIN
    IF LENGTH(I_JUMIN)!= 13 THEN
    RETURN '제대로 된 값 입력하세요';
    END IF;
    
    O_GENDER := SUBSTR(I_JUMIN,7,1);
    IF O_GENDER IN ('1','3') THEN    
       RETURN '남자';
    ELSIF O_GENDER IN('2','4') THEN
        RETURN '여자';
    ELSE 
        RETURN '외국인';
    END IF;
END;
/
SELECT JUMIN, GENDER_FUNC(JUMIN)
FROM STU;

SELECT COUNT(JUMIN)
FROM STU;