--
SELECT DECODE(SUBSTR(JUMIN,7,1),1, '남자','여자')
FROM STU;

SELECT SYSDATE
FROM DUAL;

SELECT MAX(STU_HEIGHT)
FROM STUDENT;

SELECT *
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP
);

SELECT JOB ,ROUND(AVG(SAL),2)
FROM EMP
WHERE SAL >= 1500
GROUP BY JOB
HAVING AVG(SAL) >= 2500
;

SELECT *
FROM STUDENT 
;

SELECT *
FROM ENROL
;
SELECT S.STU_NO,STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON  S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME
;


SELECT S.STU_NO, AVG(ENR_GRADE)AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON  S.STU_NO = E.STU_NO
GROUP BY S.STU_NO
;

SELECT *
FROM STUDENT S
INNER JOIN(
    SELECT S.STU_NO, AVG(ENR_GRADE)AVG_GRADE
    FROM STUDENT S
    INNER JOIN ENROL E ON  S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO   
) T ON S.STU_NO = T.STU_NO
;

SELECT S.*, ENR_GRADE
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT E1.*,E2.ENAME 매니저이름
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

SELECT * 
FROM DEPARTMENT;

SELECT *
FROM STU S 
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE NAME = '서진수';

SELECT *
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
;
SELECT *
FROM SALGRADE;