-- SEQUENCE
-- AI(AUTO INCREMENT)
CREATE SEQUENCE TEMP1_SEQ
    INCREMENT BY 1
    START WITH 1
   -- MINVALUE 1
   -- MAXVALUE 99999
   -- NOCYCLE
;

SELECT TEMP1_SEQ.NEXTVAL
FROM DUAL;

CREATE TABLE BOARD
(
    BOARDNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENTS VARCHAR2(300),
    CDATETIME DATE,
    UDATETIME DATE
); 
COMMIT;

ROLLBACK;

INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL, '333 번째 게시글', '안녕?', SYSDATE, SYSDATE);
COMMIT;

CREATE SEQUENCE BOARD_SEQ
    INCREMENT BY 1
    START WITH 1
  ;  
SELECT * FROM BOARD;