SELECT COUNT(*) FROM TBL_USER; 
SELECT COUNT(*) FROM TBL_BOARD; 
SELECT COUNT(*) FROM TBL_COMMENT;

SELECT * FROM TBL_USER; 
SELECT * FROM TBL_BOARD;

-- 게시글의 제목, 내용, 조회수, 작성자 이름.
SELECT TITLE, CONTENTS, CNT, USERNAME
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
;

-- 사용자 아이디, 이름, 해당 사용자가 작성한 댓글 개수.
SELECT * FROM TBL_USER; 
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

SELECT U.USERID, USERNAME, COUNT(*) 댓글개수
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY U.USERID, USERNAME
;

-- 작성한 게시글의 조회수 합이 가장 많은 상위 3명의 이름과 조회수 합 출력

SELECT USERID, SUM(CNT) AS SUM_CNT
FROM TBL_BOARD
GROUP BY USERID
ORDER BY SUM_CNT DESC
;

SELECT USERNAME,SUM_CNT
FROM(
    SELECT USERID, SUM(CNT) AS SUM_CNT
    FROM TBL_BOARD
    GROUP BY USERID
    ORDER BY SUM_CNT DESC

)T
INNER JOIN TBL_USER U ON T.USERID = U.USERID
WHERE ROWNUM <= 3
;

SELECT * 
FROM(
    SELECT B.USERID,USERNAME, SUM(CNT) AS SUM_CNT
    FROM TBL_BOARD B
    INNER JOIN TBL_USER U ON B.USERID = U.USERID
    GROUP BY B.USERID,USERNAME
    ORDER BY SUM_CNT DESC

)
WHERE ROWNUM <= 3
;

SELECT COUNT(*)
FROM TBL_COMMENT;

SELECT TITLE, COUNT(*)
FROM TBL_BOARD B 
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE
;


SELECT TITLE, 댓글개수
FROM(
    SELECT TITLE, COUNT(*) AS 댓글개수 ,1 AS ORDERKEY
    FROM TBL_BOARD B 
    INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO, TITLE
    UNION
    SELECT '댓글전체개수',COUNT(*), 2 AS ORDERKEY
    FROM TBL_COMMENT
    ORDER BY ORDERKEY, 댓글개수 DESC
);


