-- STUDENT, ENROL, SUBJECT
--1. 컴퓨터개론 수업을 들은 학생의 학번, 이름, 시험점수 출력
SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_NAME = '컴퓨터개론'
;
--2. 시험의 평균 점수가 70이상인 학생의 학번, 이름, 평균점수 출력
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) 평균
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING AVG(ENR_GRADE) >= 70
;
--3. 시험을 2개이상 본 학생의 학번, 이름, 시험개수 출력
SELECT S.STU_NO, STU_NAME, COUNT(*)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING COUNT(*) >= 2
;
SELECT *
FROM ENROL;

SELECT *
FROM SUBJECT;



-- PROFESSOR, STU, DEPARTMENT
-- EMP,DEPT, SALGRADE
--1. 부서 이름, 부서내의 사람들의 급여 평균 등급 출력
SELECT DNAME, ROUND(AVG(GRADE), 1)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL -- 평균을 먼저구하기.
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
;

SELECT DNAME,AVG(SAL)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
;

SELECT DNAME, GRADE
FROM (
SELECT DNAME,AVG(SAL) AS SAL_AVG
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY DNAME
) T
    INNER JOIN SALGRADE S ON T.SAL_AVG BETWEEN S.LOSAL AND S.HISAL
;
--2. 상사가 'BLAKE'인 사원들의 사번, 이름 출력
SELECT E1.EMPNO, E1.ENAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO
--WHERE E1.MGR = 7698 BLAKE 의 사번을 모른다는 가정하에.
WHERE E2.ENAME = 'BLAKE'
; 

SELECT *
FROM DEPT;

SELECT *
FROM SALGRADE;

-- '공과대학'에 속한 학생(DEPTNO1)의 수 구하기.
SELECT * FROM PROFESSOR;

SELECT D3.DNAME, COUNT(*)
FROM STU S 
    INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
    INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
    INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
    WHERE D3.DNAME = '공과대학'
    GROUP BY D3.DNAME
;

SELECT * FROM STU;
SELECT * FROM DEPARTMENT;

