-- 서브 쿼리

-- STUDENT 테이블에서 학과별 평균 키

SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1) AVG_DEPT
FROM STUDENT
GROUP BY STU_DEPT; 
-- 1-2. 학번, 이름, 학과, 키, 내가 속한 학과의 평균 키
SELECT STU_NO, STU_NAME, S.STU_DEPT, STU_HEIGHT, AVG_DEPT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1) AVG_DEPT
    FROM STUDENT
    GROUP BY STU_DEPT 
    ) T ON S.STU_DEPT = T.STU_DEPT;
    
-- 1-3. 내가 속한 학과의 평균키보다 키가 큰 학생의 학번, 이름, 학과, 키
SELECT STU_NO, STU_NAME, S.STU_DEPT, STU_HEIGHT, AVG_DEPT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1) AVG_DEPT
    FROM STUDENT
    GROUP BY STU_DEPT 
) T ON S.STU_DEPT = T.STU_DEPT
WHERE STU_HEIGHT >AVG_DEPT;    

-- EMP , DEPT
-- 내가 속한 부서 평균 급여보다 높은 급여를 받는 사람의 사번, 이름, 급여, 부서 이름
-- 속한 부서의 평균 급여 출력
SELECT E.DEPTNO, DNAME ,AVG(SAL) AVG_DEPT
FROM EMP E 
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, DNAME
;
SELECT EMPNO, ENAME, SAL, DNAME,ROUND(AVG_DEPT,1)
FROM EMP E 
INNER JOIN(
    SELECT E.DEPTNO, DNAME ,AVG(SAL) AVG_DEPT
    FROM EMP E 
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO, DNAME
)T ON E.DEPTNO = T.DEPTNO
WHERE SAL > AVG_DEPT
;

SELECT *
FROM DEPT;

SELECT *
FROM PROFESSOR;
-- 각 직급별(POSITION)별 가장 많은 급여를 받는 사람의
SELECT POSITION,MAX(PAY)MAX_PAY
FROM PROFESSOR
GROUP BY POSITION


;
-- 교수번호, 이름, 급여 출력
SELECT P.PROFNO, P.NAME, PAY
FROM PROFESSOR P
INNER JOIN(
    SELECT POSITION,MAX(PAY) MAX_PAY
    FROM PROFESSOR
    GROUP BY POSITION
) T ON P.POSITION = T.POSITION AND P.PAY = T.MAX_PAY
    ;





-- 본인 학부의 평균 급여보다 높은 급여를 받는 교수의 교수번호, 이름, 급여 출력
SELECT D2.DNAME, ROUND(AVG(PAY))
FROM PROFESSOR P 
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
GROUP BY D2.DNAME

;

SELECT NAME, D2.DNAME,PAY,AVG_PAY
FROM PROFESSOR P 
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN (
    SELECT D2.DNAME, ROUND(AVG(PAY),2) AS AVG_PAY
    FROM PROFESSOR P 
    INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
    INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
    GROUP BY D2.DNAME
) T ON D2.DNAME = T.DNAME
WHERE PAY > AVG_PAY
;

-- EMP 테이블
-- 부서별 가장 높은 급여를 받는 사람의 사번, 이름, 급여 출력
SELECT *
FROM EMP;

SELECT DEPTNO,MAX(SAL) MAX_SAL
FROM EMP
GROUP BY DEPTNO;

SELECT EMPNO, ENAME, SAL
FROM EMP E
INNER JOIN (
    SELECT DEPTNO,MAX(SAL)MAX_SAL
    FROM EMP
    GROUP BY DEPTNO
)T ON E.DEPTNO = T.DEPTNO AND E.SAL = T.MAX_SAL
--WHERE SAL = MAX_SAL
;

-- STUDENT
-- 학과 별 가장 큰 키를 가진 학생의 학번,이름,키 출력
SELECT *
FROM STUDENT;

SELECT STU_DEPT, MAX(STU_HEIGHT)MAX_HEIGHT
FROM STUDENT
GROUP BY STU_DEPT;

SELECT STU_NO,STU_NAME,STU_HEIGHT
FROM STUDENT S 
INNER JOIN(
    SELECT STU_DEPT, MAX(STU_HEIGHT)MAX_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
)T ON S.STU_DEPT = T.STU_DEPT AND S.STU_HEIGHT = T.MAX_HEIGHT ;
--WHERE STU_DEPT = MAX_HEIGHT;


-- STUDENT
-- 학과 별 가장 큰 키를 가진 학생의 학번,이름,키 출력

SELECT STU_DEPT,MAX(STU_HEIGHT) MAX_HEIGHT
FROM STUDENT
GROUP BY STU_DEPT;

SELECT *
FROM STUDENT S
INNER JOIN(
    SELECT STU_DEPT,MAX(STU_HEIGHT) MAX_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
)T ON S.STU_DEPT = T.STU_DEPT AND S.STU_HEIGHT = T.MAX_HEIGHT
;

SELECT *
FROM STU;

-- 앞 두글자 학번별로 평균 키

SELECT SUBSTR(STUNO,1,2),AVG(HEIGHT)
FROM STU
GROUP BY SUBSTR(STUNO,1,2)
;

SELECT *
FROM STU;

-- 남자와 여자의 평균 키 출력
SELECT DECODE(SUBSTR(JUMIN,7,1), 1, '남자',3,'남자', '여자') 성별 ,ROUND(AVG(HEIGHT),1) 평균
FROM STU
GROUP BY SUBSTR(JUMIN,7,1);

--













