-- OUTER JOIN(LEFT, RIGHT)
-- LEFT 는 앞에있는 테이블을 기준으로 조인
-- FROM STU S -> 기준
-- LEFT JOIN DEPT D
-- RIGHT 는 뒤에 있는 테이블을 기준으로 조인
-- FROM STU S
-- RIGHT JOIN DEPT D -> 기준
-- 기준이 되는 테이블의 정보는 조건에 상관없이 모두 출력.
SELECT * 
FROM PROFESSOR P;

SELECT * FROM STU;


SELECT P.NAME, P.POSITION,NVL(S.NAME, '담당학생없음')
FROM PROFESSOR P
LEFT JOIN STU S ON P.PROFNO = S.PROFNO
;

-- 학번, 학생 이름, 담당교수 이름 출력
-- 담당 교수가 없으면 '없음'으로 출력
SELECT STUNO, S.NAME, NVL(P.NAME, '없음')
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
;

--NVL로 대체되는 인자값의 타입은 같은 타입이어야함.

SELECT STU_NAME, NVL(TO_CHAR(AVG(ENR_GRADE)), '점수 없음')
FROM STUDENT S 
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
;

-- EMP
-- 부하 직원의 수 
-- 없으면 0으로 출력
-- 사번, 이름, 자신의 부하직원 수 출력
SELECT MGR, COUNT(*)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;

SELECT EMPNO,ENAME,NVL(CNT, 0) AS CNT
FROM EMP E
LEFT JOIN(
    SELECT MGR, COUNT(*)AS CNT
    FROM EMP
    WHERE MGR IS NOT NULL
    GROUP BY MGR
)T ON T.MGR = E.EMPNO
ORDER BY CNT DESC
;

SELECT EMPNO,ENAME,B
FROM STU;

SELECT *
FROM DEPT;

SELECT *
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
;

--
SELECT * FROM PROFESSOR;

SELECT 
    INSTR(EMAIL, '@'),
    SUBSTR(EMAIL, INSTR(EMAIL, '@')) ,
    LPAD(SUBSTR(EMAIL, INSTR(EMAIL, '@')), LENGTH(EMAIL),'*')
    
FROM PROFESSOR;


RPAD(SUBSTR(EMAIL,INSTR(EMAIL,'.'), LENGTH(EMAIL),'.'));
SELECT * FROM 
PROFESSOR P1
INNER JOIN(
SELECT 
    INSTR(EMAIL, '@'),
    SUBSTR(EMAIL, INSTR(EMAIL, '@')) AS SUB,
    LPAD(SUBSTR(EMAIL, INSTR(EMAIL, '@')), LENGTH(EMAIL),'*')
FROM PROFESSOR
) T ON INSTR(P1.SUB,'.')  ;

SELECT 
    EMAIL,
    RPAD('*', INSTR(EMAIL,'@')-1, '*') ||
    '@' ||
    RPAD('*', INSTR(EMAIL,'.') - INSTR(EMAIL,'@') - 1, '*') ||
    SUBSTR(EMAIL, INSTR(EMAIL,'.')) AS MASK_EMAIL
FROM PROFESSOR;


SELECT 
    EMAIL,
    RPAD('*', INSTR(EMAIL, '@')-1,'*') ||
    '@' ||
    RPAD('*', INSTR(EMAIL, '.') - INSTR(EMAIL,'@')-1,'*') ||
    SUBSTR(EMAIL,INSTR(EMAIL,'.')) AS SECRETEMAIL
FROM PROFESSOR;






