-- EMP , DEPT
-- 내가 속한 부서 평균 급여보다 높은 급여를 받는 사람의 사번, 이름, 급여, 부서 이름
-- 속한 부서의 평균 급여 출력
SELECT E.DEPTNO,AVG(SAL) AVG_DEPT
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO
;

SELECT EMPNO,ENAME,SAL,E.DEPTNO,ROUND(AVG_DEPT,1)
FROM EMP E
INNER JOIN(
    SELECT E.DEPTNO,AVG(SAL) AVG_DEPT
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO
)T ON E.DEPTNO = T.DEPTNO
WHERE SAL > AVG_DEPT
;